### ISSUE TITLE
run inference failed

### ISSUE THREAD

**Issue by Saibo-creator** [epfl-dlab/SynthIE#2]
## Reproduction:

Following the example given in the inference section in the README.md
```terminal
MODEL=synthie_base_fe # synthie_base_fe, synthie_base_sc, synthie_large_fe, genie_base_fe

# The name of the dataset
DATAMODULE=rebel_pc  # "rebel_pc", "sdg_code_davinci_002_pc", "sdg_text_davinci_003_pc"

python run_inference.py +experiment/inference=$MODEL datamodule=$DATAMODULE
```

Error message:

```terminal
Traceback (most recent call last):
  File "/home/saibo/.conda/envs/synthie/lib/python3.8/site-packages/hydra/_internal/utils.py", line 639, in _locate
    obj = getattr(obj, part)
AttributeError: module 'src' has no attribute 'models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/saibo/.conda/envs/synthie/lib/python3.8/site-packages/hydra/_internal/utils.py", line 645, in _locate
    obj = import_module(mod)
  File "/home/saibo/.conda/envs/synthie/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/saibo/Research/Rotation2/SynthIE/src/models/__init__.py", line 1, in <module>
    from .genie_flan_t5 import GenIEFlanT5PL
  File "/home/saibo/Research/Rotation2/SynthIE/src/models/genie_flan_t5.py", line 15, in <module>
    from src.metrics import TSF1, TSPrecision, TSRecall
  File "/home/saibo/Research/Rotation2/SynthIE/src/metrics/__init__.py", line 1, in <module>
    from .triplet_set_f1 import TSF1
  File "/home/saibo/Research/Rotation2/SynthIE/src/metrics/triplet_set_f1.py", line 4, in <module>
    from src.metrics.abstract import IEAbstractTorchMetric
  File "/home/saibo/Research/Rotation2/SynthIE/src/metrics/abstract.py", line 9, in <module>
    class IEAbstractTorchMetric(Metric, ABC):
  File "/home/saibo/Research/Rotation2/SynthIE/src/metrics/abstract.py", line 72, in IEAbstractTorchMetric
    ) -> Union[float, dict[str, float]]:
TypeError: 'type' object is not subscriptable

```

## Fix

In `SynthIE/src/metrics/abstract.py:72, in IEAbstractTorchMetric()`
replace `Union[float, dict[str, float]]` by Union[float, Dict[str, float]]

because `dict` is not a type, but `Dict`

**Comment by martinj96** [comment]
Thanks for the fix Saibo!
